name: CI
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    perform-checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                cache: true
            - name: Show Flutter version
              run: flutter --version
            - name: Get dependencies
              run: |
                flutter pub get
                flutter analyze
                dart format --set-exit-if-changed --enable-experiment=digit-separators .
                flutter test
    build-android:
        needs: perform-checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '17'
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                cache: true
            - name: Build Android appbundle
              run: flutter build appbundle --debug 
    build-ios:
      needs: perform-checks
      runs-on: macos-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              cache: true
          - name: Build ios
            run: flutter build ios --debug --no-codesign 